# Generated by Django 4.2 on 2025-01-10 16:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
        ('shared_features', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='JobPosting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_removed', models.BooleanField(default=False)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('expiry_date', models.DateField()),
                ('salary_range_start', models.PositiveIntegerField(blank=True, null=True)),
                ('salary_range_end', models.PositiveIntegerField(blank=True, null=True)),
                ('working_hours', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='JobPostingPhoto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_removed', models.BooleanField(default=False)),
                ('file_path', models.ImageField(upload_to='job_posting_photos/')),
                ('is_active', models.BooleanField(default=False)),
                ('job_posting', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='job_posting_photo_job_posting', to='jobs.jobposting')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='jobposting',
            name='active_photo',
            field=models.ForeignKey(blank=True, help_text='Current active photo for the job posting.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='job_posting_active_photo', to='jobs.jobpostingphoto'),
        ),
        migrations.AddField(
            model_name='jobposting',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='job_posting_company', to='accounts.company'),
        ),
        migrations.AddField(
            model_name='jobposting',
            name='industry_areas',
            field=models.ManyToManyField(related_name='job_posting_industry_areas', to='accounts.industryarea'),
        ),
        migrations.AddField(
            model_name='jobposting',
            name='skills',
            field=models.ManyToManyField(related_name='job_posting_skills', to='shared_features.skill'),
        ),
        migrations.CreateModel(
            name='Application',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_removed', models.BooleanField(default=False)),
                ('application_date', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('Pending', 'Pending'), ('Accepted', 'Accepted'), ('Rejected', 'Rejected')], default='Pending', max_length=20)),
                ('job_posting', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='applications_job_posting', to='jobs.jobposting')),
                ('job_seeker', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='applications_job_seeker', to='accounts.jobseeker')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddIndex(
            model_name='jobposting',
            index=models.Index(fields=['title'], name='jobs_jobpos_title_afd3ed_idx'),
        ),
        migrations.AddIndex(
            model_name='jobposting',
            index=models.Index(fields=['company'], name='jobs_jobpos_company_af0424_idx'),
        ),
    ]
