# Generated by Django 4.2 on 2025-01-10 17:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='user_type',
        ),
        migrations.AddField(
            model_name='user',
            name='is_staff',
            field=models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.'),
        ),
        migrations.AddField(
            model_name='user',
            name='usage_type',
            field=models.CharField(blank=True, choices=[('JobSeeker', 'Job Seeker'), ('Employer', 'Employer'), ('Staff', 'Staff'), ('SuperUser', 'SuperUser')], default='JobSeeker', help_text='Type of user (JobSeeker or Employer).', max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='is_superuser',
            field=models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.'),
        ),
    ]
