# Generated by Django 4.2 on 2025-01-10 17:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_remove_user_user_type_user_is_staff_user_usage_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='usage_type',
            field=models.CharField(blank=True, choices=[('JobSeeker', 'Job Seeker'), ('Employer', 'Employer')], default='JobSeeker', help_text='Type of user (JobSeeker or Employer).', max_length=10, null=True),
        ),
    ]
