# Generated by Django 4.2 on 2025-01-10 17:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_alter_user_usage_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='usage_type',
            field=models.CharField(blank=True, choices=[('JobSeeker', 'Job Seeker'), ('Employer', 'Employer')], help_text='Type of user (JobSeeker or Employer).', max_length=10, null=True),
        ),
    ]
